### ISSUE TITLE
Sync error with a UFVK with NO transparent receiver

### ISSUE THREAD

**Issue by juanky201271** [zingolabs/zingolib#1471]
UFVK with **no transparent receiver**:

uview1rmha9wzdh8c7geh5e62eqzx8u08hxycpfj0qfugv5pmslpflrcscjqh49vryfzyv2846necwchztjps3856uap6vkfq9ncnna2hn9gzxgc4lr8ega2rst4pvmn5w9tqsaztk749k8496qljsh4v3lmmtak4g62mcus43trk29js8nr7ez99frq7zgk4pdn3jpgyhk7utr8njnljmj08ggh58rk5lvu9j6h2j47wuk7qqaeq4lzwexhlekyl9y9xnmha8fszqpmv6mes2njxzx0568vkm7zagcm320wcvxr6pq3fr7cx3kcjsdkf99f7z6naev8urhljkq0xcf0chyr59kf2lvp9h34s7sxam4pt9mflftkqe4f6rqvfnhtj020q0grs5r5feh

birthday: 2300000

Error:
**sync finished task 14231 panicked with message "Zingo Memo data has been successfully applied without error.: InvalidRejectionAddress(NoViewCapability)"**

Command:
`.\target\release\zingo-cli.exe --viewkey "uview1rmha9wzdh8c7geh5e62eqzx8u08hxycpfj0qfugv5pmslpflrcscjqh49vryfzyv2846necwchztjps3856uap6vkfq9ncnna2hn9gzxgc4lr8ega2rst4pvmn5w9tqsaztk749k8496qljsh4v3lmmtak4g62mcus43trk29js8nr7ez99frq7zgk4pdn3jpgyhk7utr8njnljmj08ggh58rk5lvu9j6h2j47wuk7qqaeq4lzwexhlekyl9y9xnmha8fszqpmv6mes2njxzx0568vkm7zagcm320wcvxr6pq3fr7cx3kcjsdkf99f7z6naev8urhljkq0xcf0chyr59kf2lvp9h34s7sxam4pt9mflftkqe4f6rqvfnhtj020q0grs5r5feh" --birthday 2300000`

NOTE: This error is not happening with a UFVK with all receivers.

**Comment by juanky201271** [comment]
![image](https://github.com/user-attachments/assets/05a544c1-c62c-49c0-8756-0f7208d863e3)

Text:
```
**Batch** Current: 3838 Total: 3956
   **Blocks** Current Height: 2683900
**Batch** Current: 3850 Total: 3956
   **Blocks** Current Height: 2685100
thread 'tokio-runtime-worker' panicked at zingolib\src\wallet\transaction_context.rs:149:18:
Zingo Memo data has been successfully applied without error.: InvalidRejectionAddress(NoViewCapability)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at zingolib\src\wallet\transaction_context.rs:149:18:
Zingo Memo data has been successfully applied without error.: InvalidRejectionAddress(NoViewCapability)
sync hit error task 229272 panicked. Rolling back
task 229272 panicked
(main) Block:2685599 (type 'help') >> thread 'tokio-runtime-worker' panicked at zingolib\src\wallet\transaction_context.rs:149:18:
Zingo Memo data has been successfully applied without error.: InvalidRejectionAddress(NoViewCapability)
thread 'tokio-runtime-worker' panicked at zingolib\src\wallet\transaction_context.rs:149:18:
Zingo Memo data has been successfully applied without error.: InvalidRejectionAddress(NoViewCapability)
sync hit error task 229431 panicked. Rolling back
thread 'tokio-runtime-worker' panicked at zingolib\src\wallet\transaction_context.rs:149:18:
Zingo Memo data has been successfully applied without error.: InvalidRejectionAddress(NoViewCapability)
thread 'tokio-runtime-worker' panicked at zingolib\src\wallet\transaction_context.rs:149:18:
Zingo Memo data has been successfully applied without error.: InvalidRejectionAddress(NoViewCapability)
sync hit error task 229572 panicked. Rolling back
```

**Comment by Oscar-Pepper** [comment]
rewritten for 2.0
