### ISSUE TITLE
Failed to fill whole buffer when opening previously created wallet

### ISSUE THREAD

**Issue by pacu** [zingolabs/zingolib#323]
reported with @felipeberizovsky

Reproducibility: Low

linux: lubuntu
commit: 537582634cb23e0831f54e34e6d78e472a7fbca5

Steps to reproduce:

1. create a new wallet testnet wallet with a data dir in cli mode
2. get the balance
3. close the wallet

do something else like grabbing a tea.

Then try to open the same wallet again `RUST_BACKTRACE=full ./target/release/zingo-cli --server=https://testnet.lightwalletd.com:9067 --data-dir ~/Download/tbd_A1`

expected:  wallet works as usual

Result:
````

RUST_BACKTRACE=full ./target/release/zingo-cli --server=https://testnet.lightwalletd.com:9067 --data-dir ~/Download/tbd_A1
Error during startup:
failed to fill whole buffer
If you repeatedly run into this issue, you might have to restore your wallet from your seed phrase.
2023-04-25T22:19:11.994492Z ERROR zingo_cli: Error during startup:
failed to fill whole buffer
If you repeatedly run into this issue, you might have to restore your wallet from your seed phrase.    
thread 'main' panicked at 'explicit panic', zingocli/src/lib.rs:485:13
stack backtrace:
   0:     0x559ecf46eb2a - std::backtrace_rs::backtrace::libunwind::trace::ha9053a9a07ca49cb
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x559ecf46eb2a - std::backtrace_rs::backtrace::trace_unsynchronized::h9c2852a457ad564e
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x559ecf46eb2a - std::sys_common::backtrace::_print_fmt::h457936fbfaa0070f
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x559ecf46eb2a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5779d7bf7f70cb0c
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x559ecf49790e - core::fmt::write::h5a4baaff1bcd3eb5
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/fmt/mod.rs:1232:17
   5:     0x559ecf46ad75 - std::io::Write::write_fmt::h4bc1f301cb9e9cce
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/io/mod.rs:1684:15
   6:     0x559ecf46e8f5 - std::sys_common::backtrace::_print::h5fcdc36060f177e8
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x559ecf46e8f5 - std::sys_common::backtrace::print::h54ca9458b876c8bf
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x559ecf4700af - std::panicking::default_hook::{{closure}}::hbe471161c7664ed6
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:271:22
   9:     0x559ecf46fdeb - std::panicking::default_hook::ha3500da57aa4ac4f
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:290:9
  10:     0x559ecf470658 - std::panicking::rust_panic_with_hook::h50c09d000dc561d2
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:692:13
  11:     0x559ecf470512 - std::panicking::begin_panic_handler::{{closure}}::h9e2b2176e00e0d9c
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:581:13
  12:     0x559ecf46ef96 - std::sys_common::backtrace::__rust_end_short_backtrace::h5739b8e512c09d02
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:150:18
  13:     0x559ecf470262 - rust_begin_unwind
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
  14:     0x559ece930503 - core::panicking::panic_fmt::hf33a1475b4dc5c3e
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
  15:     0x559ece93059d - core::panicking::panic::h9533b2fee90b999e
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:114:5
  16:     0x559ece939c6d - zingo_cli::run_cli::h5f75d9ec6ed72c0f
  17:     0x559ece930c13 - std::sys_common::backtrace::__rust_begin_short_backtrace::hb8a9a8848f801eb2
  18:     0x559ece930c69 - std::rt::lang_start::{{closure}}::h5189cb6f5fb78870
  19:     0x559ecf46520c - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hd6efcd3bec896f2c
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ops/function.rs:287:13
  20:     0x559ecf46520c - std::panicking::try::do_call::hce04e543bb1f4cbb
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:487:40
  21:     0x559ecf46520c - std::panicking::try::h3342dd4e1f680968
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:451:19
  22:     0x559ecf46520c - std::panic::catch_unwind::h148ce1e59ac0cee7
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panic.rs:140:14
  23:     0x559ecf46520c - std::rt::lang_start_internal::{{closure}}::h25f9dda2057a67fe
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/rt.rs:148:48
  24:     0x559ecf46520c - std::panicking::try::do_call::h7caaaeaf9401650b
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:487:40
  25:     0x559ecf46520c - std::panicking::try::he7d15285746cbbc2
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:451:19
  26:     0x559ecf46520c - std::panic::catch_unwind::h89fb4f50c0301fe0
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panic.rs:140:14
  27:     0x559ecf46520c - std::rt::lang_start_internal::h078acd489417d3c1
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/rt.rs:148:20
  28:     0x559ece930c55 - main
  29:     0x7f5107429d90 - <unknown>
  30:     0x7f5107429e40 - __libc_start_main
  31:     0x559ece930b45 - _start
  32:                0x0 - <unknown>
````

**Comment by zancas** [comment]
Hi @AloeareV is this an issue in the current codebase?   We should either add it to:

https://github.com/zingolabs/zingolib/milestone/1

and label it `bug`...

Or close the issue.
